(function(win,doc){'use strict';
var every=3*60*1000;
function id(x){return doc.getElementById(x)} function text(x,v){id(x).textContent=String(v==null?'':v)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function number(v){var n=Number(v||0);return isFinite(n)?String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g,','):'0'}
function compact(v){var n=Number(v||0);if(n>=1000000000)return (n/1000000000).toFixed(1)+'B';if(n>=1000000)return (n/1000000).toFixed(1)+'M';if(n>=1000)return (n/1000).toFixed(1)+'K';return String(Math.round(n))}
function reset(v){var t=Date.parse(v||'');if(!isFinite(t))return '重置时间未知';var s=Math.max(0,Math.floor((t-Date.now())/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?d+'天'+h+'小时后重置':h?h+'小时'+m+'分钟后重置':m+'分钟后重置'}
function windows(src){var a=src&&src.windows||[],out='';for(var i=0;i<a.length;i++){var w=a[i],u=Math.max(0,Math.min(100,Number(w.usedPct||0))),r=100-Math.round(u);out+='<div class="window"><div class="label"><span>'+esc(w.name)+'</span><span>剩余 '+r+'%</span></div><div class="bar"><div class="fill" style="width:'+u+'%"></div></div><div class="reset">'+esc(reset(w.resetAt))+'</div></div>'}return out||'<div class="error">没有可显示的额度窗口</div>'}
function chart(name,rows){var node=id(name),a=Array.isArray(rows)?rows.slice(-5):[],max=1,out='';for(var i=0;i<a.length;i++)max=Math.max(max,Number(a[i].tokens||0));if(!a.length){node.innerHTML='<div class="error">暂无历史 token 数据</div>';return}for(var j=0;j<a.length;j++){var n=Number(a[j].tokens||0),h=n?Math.max(3,Math.round(n/max*100)):0;out+='<div class="col"><div class="bar-v"><i style="height:'+h+'%"></i></div><div>'+esc(String(a[j].date).slice(5))+'</div><div>'+esc(compact(n))+'</div></div>'}node.innerHTML=out}
function render(data){if(!data||!data.sources)return;var c=data.sources.codex||{},d=data.sources.deepseek||{};text('codexStatus',c.ok?'已连接':c.disabled?'未启用':'采集失败');text('deepseekStatus',d.ok?'已连接':d.disabled?'未启用':'采集失败');id('codexWindows').innerHTML=c.ok?windows(c):'<div class="error">'+esc(c.error||'没有数据')+'</div>';if(d.ok){text('deepseekBalance',(d.currency==='CNY'?'¥ ':'')+Number(d.balance).toFixed(2));text('deepseekDetail',d.detail||'实时余额')}else{text('deepseekBalance','¥ --');text('deepseekDetail',d.error||'没有数据')}chart('codexChart',data.usageHistory&&data.usageHistory.codex);var m=String(data.updatedAt||'').match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/);text('updated',m?m[1]+'年'+Number(m[2])+'月'+Number(m[3])+'日 '+m[4]+':'+m[5]+' 更新':'更新时间未知')}
function load(){var s=doc.createElement('script');s.src='data.js?_='+Date.now();s.onload=function(){render(win.DASH_DATA)};doc.body.appendChild(s)}
render(win.DASH_DATA);win.setInterval(load,every);
}(window,document));
